rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
notifications:
  irc: "irc.freenode.org#cells"
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
